/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Marcielli
 */
public class Cadastro extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelTopoCadastro = new javax.swing.JPanel();
        lbTopoCadastro = new javax.swing.JLabel();
        jLabelTopoCadastro = new javax.swing.JLabel();
        jLabelImgTopoCadastro = new javax.swing.JLabel();
        jPanelRodapeCadastro = new javax.swing.JPanel();
        jLabelRodapeCadastro = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lbCadNome = new javax.swing.JLabel();
        txtCadNome = new javax.swing.JTextField();
        lbCadEmail = new javax.swing.JLabel();
        txtCadEmail = new javax.swing.JTextField();
        lbCadCurso = new javax.swing.JLabel();
        jComboBoxCadCurso = new javax.swing.JComboBox<>();
        jComboBoxCadPeriodo = new javax.swing.JComboBox<>();
        lbCadPeriodo = new javax.swing.JLabel();
        lbCadFaculdade = new javax.swing.JLabel();
        jComboBoxCadFaculdade = new javax.swing.JComboBox<>();
        lbCadRAaluno = new javax.swing.JLabel();
        txtCadRAaluno = new javax.swing.JTextField();
        lbCadNumInscProf = new javax.swing.JLabel();
        txtCadNumInscProf = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabeCadCorujaMudando = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanelTopoCadastro.setBackground(new java.awt.Color(6, 161, 196));

        lbTopoCadastro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTopoCadastro.setForeground(new java.awt.Color(255, 255, 255));
        lbTopoCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTopoCadastro.setText("Bom Dia, Nome.");

        jLabelTopoCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/logos/logo-topo.png"))); // NOI18N

        jLabelImgTopoCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/logos/topo_escrevendo.png"))); // NOI18N

        javax.swing.GroupLayout jPanelTopoCadastroLayout = new javax.swing.GroupLayout(jPanelTopoCadastro);
        jPanelTopoCadastro.setLayout(jPanelTopoCadastroLayout);
        jPanelTopoCadastroLayout.setHorizontalGroup(
            jPanelTopoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopoCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTopoCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTopoCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(jLabelImgTopoCadastro)
                .addGap(20, 20, 20))
        );
        jPanelTopoCadastroLayout.setVerticalGroup(
            jPanelTopoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopoCadastroLayout.createSequentialGroup()
                .addGroup(jPanelTopoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTopoCadastroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelTopoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelImgTopoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTopoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelTopoCadastroLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lbTopoCadastro)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelRodapeCadastro.setBackground(new java.awt.Color(6, 161, 196));

        jLabelRodapeCadastro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelRodapeCadastro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRodapeCadastro.setText("ABEP Educa. 2016");

        javax.swing.GroupLayout jPanelRodapeCadastroLayout = new javax.swing.GroupLayout(jPanelRodapeCadastro);
        jPanelRodapeCadastro.setLayout(jPanelRodapeCadastroLayout);
        jPanelRodapeCadastroLayout.setHorizontalGroup(
            jPanelRodapeCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRodapeCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRodapeCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRodapeCadastroLayout.setVerticalGroup(
            jPanelRodapeCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRodapeCadastroLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabelRodapeCadastro)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(6, 161, 196))); // NOI18N

        lbCadNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCadNome.setForeground(new java.awt.Color(6, 161, 196));
        lbCadNome.setText("Nome");

        txtCadNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 161, 196), 1, true));

        lbCadEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCadEmail.setForeground(new java.awt.Color(6, 161, 196));
        lbCadEmail.setText("Email");

        txtCadEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 161, 196), 1, true));

        lbCadCurso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCadCurso.setForeground(new java.awt.Color(6, 161, 196));
        lbCadCurso.setText("Curso");

        jComboBoxCadCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Análise e Desenvolvimento de Sistemas", "Gestão Empresarial", "Eventos", "Gestão de Produção Empresarial" }));
        jComboBoxCadCurso.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 161, 196), 1, true));

        jComboBoxCadPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manhã", "Tarde", "Noite" }));
        jComboBoxCadPeriodo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 161, 196), 1, true));

        lbCadPeriodo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCadPeriodo.setForeground(new java.awt.Color(6, 161, 196));
        lbCadPeriodo.setText("Período");

        lbCadFaculdade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCadFaculdade.setForeground(new java.awt.Color(6, 161, 196));
        lbCadFaculdade.setText("Faculdade");

        jComboBoxCadFaculdade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fatec Cruzeiro", "Fatec Guará", "Fatec São Paulo" }));
        jComboBoxCadFaculdade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 161, 196), 1, true));

        lbCadRAaluno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCadRAaluno.setForeground(new java.awt.Color(6, 161, 196));
        lbCadRAaluno.setText("R.A.");

        txtCadRAaluno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 161, 196), 1, true));

        lbCadNumInscProf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCadNumInscProf.setForeground(new java.awt.Color(6, 161, 196));
        lbCadNumInscProf.setText("Número de Inscrição do Professor");

        txtCadNumInscProf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 161, 196), 1, true));

        btnCadastrar.setBackground(new java.awt.Color(6, 161, 196));
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(6, 161, 196));
        jLabel1.setText("- OU -");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lbCadNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCadNome))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lbCadEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCadEmail))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lbCadCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCadCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(lbCadFaculdade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCadFaculdade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lbCadPeriodo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxCadPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lbCadRAaluno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCadRAaluno, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCadNumInscProf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCadNumInscProf, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCadastrar)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCadNome)
                    .addComponent(txtCadNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCadEmail)
                    .addComponent(txtCadEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCadCurso)
                    .addComponent(jComboBoxCadCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCadFaculdade)
                    .addComponent(jComboBoxCadFaculdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCadPeriodo)
                    .addComponent(jComboBoxCadPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCadRAaluno)
                    .addComponent(txtCadRAaluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lbCadNumInscProf)
                    .addComponent(txtCadNumInscProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnCadastrar)
                .addGap(65, 65, 65))
        );

        jLabeCadCorujaMudando.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeCadCorujaMudando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/1CadCoruja.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTopoCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelRodapeCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabeCadCorujaMudando, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelTopoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabeCadCorujaMudando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelRodapeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1202, 620);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JComboBox<String> jComboBoxCadCurso;
    private javax.swing.JComboBox<String> jComboBoxCadFaculdade;
    private javax.swing.JComboBox<String> jComboBoxCadPeriodo;
    private javax.swing.JLabel jLabeCadCorujaMudando;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelImgTopoCadastro;
    private javax.swing.JLabel jLabelRodapeCadastro;
    private javax.swing.JLabel jLabelTopoCadastro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelRodapeCadastro;
    private javax.swing.JPanel jPanelTopoCadastro;
    private javax.swing.JLabel lbCadCurso;
    private javax.swing.JLabel lbCadEmail;
    private javax.swing.JLabel lbCadFaculdade;
    private javax.swing.JLabel lbCadNome;
    private javax.swing.JLabel lbCadNumInscProf;
    private javax.swing.JLabel lbCadPeriodo;
    private javax.swing.JLabel lbCadRAaluno;
    private javax.swing.JLabel lbTopoCadastro;
    private javax.swing.JTextField txtCadEmail;
    private javax.swing.JTextField txtCadNome;
    private javax.swing.JTextField txtCadNumInscProf;
    private javax.swing.JTextField txtCadRAaluno;
    // End of variables declaration//GEN-END:variables
}
