/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Marcielli
 */
public class FeedProfessor extends javax.swing.JInternalFrame {

    /**
     * Creates new form FeedProfessor
     */
    public FeedProfessor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUltimasConquistasFeedProf1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanelTopoPaginaInicial = new javax.swing.JPanel();
        lbTopoPaginaInicial = new javax.swing.JLabel();
        jLabelTopoPaginaInicial = new javax.swing.JLabel();
        jLabelImgTopoPaginaInicial = new javax.swing.JLabel();
        jPanelRodapePaginaInicial = new javax.swing.JPanel();
        jLabelRodapePaginaInicial = new javax.swing.JLabel();
        labelMenuInicio = new javax.swing.JLabel();
        labelMenuDisciplinas = new javax.swing.JLabel();
        labelMenuCalendario = new javax.swing.JLabel();
        labelMenuForum = new javax.swing.JLabel();
        labelMenuQuiz = new javax.swing.JLabel();
        labelMenuMinhaEstante = new javax.swing.JLabel();
        labelMenuConquistas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaQualSuaDuvida = new javax.swing.JTextArea();
        labelMenuNotificacoes = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        panelBGUltimosBadgetsFeedProf = new javax.swing.JPanel();
        labelUltimosBadgetsFeedProf = new javax.swing.JLabel();
        labelBadget1 = new javax.swing.JLabel();
        labelBadget2 = new javax.swing.JLabel();
        labelBadget3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lagelPergunta1 = new javax.swing.JLabel();
        panelBGUltimasPerguntasFeedProf = new javax.swing.JPanel();
        labelUltimasPerguntasFeedProf = new javax.swing.JLabel();
        lagelPergunta2 = new javax.swing.JLabel();
        lagelPergunta3 = new javax.swing.JLabel();
        lagelPergunta4 = new javax.swing.JLabel();
        lagelPergunta5 = new javax.swing.JLabel();
        lagelPergunta6 = new javax.swing.JLabel();
        lagelPergunta7 = new javax.swing.JLabel();
        lagelPergunta8 = new javax.swing.JLabel();
        lagelPergunta9 = new javax.swing.JLabel();
        lagelPergunta10 = new javax.swing.JLabel();
        lagelPergunta11 = new javax.swing.JLabel();
        panelBGDuvidaPostada = new javax.swing.JPanel();
        panelBGRodapeDuvidaPostada = new javax.swing.JPanel();
        labelMateriaTopoDuvidaPostada1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        panelBGTopoPerguntaPostada = new javax.swing.JPanel();
        labelMateriaTopoDuvidaPostada = new javax.swing.JLabel();
        labelProfessorTopoDuvidaPostada = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        labelUltimasConquistasFeedProf1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelUltimasConquistasFeedProf1.setForeground(new java.awt.Color(255, 255, 255));
        labelUltimasConquistasFeedProf1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUltimasConquistasFeedProf1.setText("Últimas Conquistas");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Feed Professor");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanelTopoPaginaInicial.setBackground(new java.awt.Color(6, 161, 196));

        lbTopoPaginaInicial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTopoPaginaInicial.setForeground(new java.awt.Color(255, 255, 255));
        lbTopoPaginaInicial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTopoPaginaInicial.setText("Bom Dia, Nome.");

        jLabelTopoPaginaInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/logos/logo-topo.png"))); // NOI18N

        jLabelImgTopoPaginaInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/perfil/professor/eduardo-enari.png"))); // NOI18N

        javax.swing.GroupLayout jPanelTopoPaginaInicialLayout = new javax.swing.GroupLayout(jPanelTopoPaginaInicial);
        jPanelTopoPaginaInicial.setLayout(jPanelTopoPaginaInicialLayout);
        jPanelTopoPaginaInicialLayout.setHorizontalGroup(
            jPanelTopoPaginaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopoPaginaInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTopoPaginaInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTopoPaginaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(jLabelImgTopoPaginaInicial)
                .addGap(20, 20, 20))
        );
        jPanelTopoPaginaInicialLayout.setVerticalGroup(
            jPanelTopoPaginaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopoPaginaInicialLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanelTopoPaginaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelImgTopoPaginaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTopoPaginaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelTopoPaginaInicialLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lbTopoPaginaInicial)))
                .addContainerGap())
        );

        jPanelRodapePaginaInicial.setBackground(new java.awt.Color(6, 161, 196));

        jLabelRodapePaginaInicial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelRodapePaginaInicial.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRodapePaginaInicial.setText("ABEP Educa. 2016");

        javax.swing.GroupLayout jPanelRodapePaginaInicialLayout = new javax.swing.GroupLayout(jPanelRodapePaginaInicial);
        jPanelRodapePaginaInicial.setLayout(jPanelRodapePaginaInicialLayout);
        jPanelRodapePaginaInicialLayout.setHorizontalGroup(
            jPanelRodapePaginaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRodapePaginaInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRodapePaginaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelRodapePaginaInicialLayout.setVerticalGroup(
            jPanelRodapePaginaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRodapePaginaInicialLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabelRodapePaginaInicial)
                .addGap(19, 19, 19))
        );

        labelMenuInicio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelMenuInicio.setForeground(new java.awt.Color(6, 161, 196));
        labelMenuInicio.setText("Início");

        labelMenuDisciplinas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelMenuDisciplinas.setForeground(new java.awt.Color(6, 161, 196));
        labelMenuDisciplinas.setText("Disciplinas");

        labelMenuCalendario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelMenuCalendario.setForeground(new java.awt.Color(6, 161, 196));
        labelMenuCalendario.setText("Calendário");

        labelMenuForum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelMenuForum.setForeground(new java.awt.Color(6, 161, 196));
        labelMenuForum.setText("Forum");

        labelMenuQuiz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelMenuQuiz.setForeground(new java.awt.Color(6, 161, 196));
        labelMenuQuiz.setText("Quiz");

        labelMenuMinhaEstante.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelMenuMinhaEstante.setForeground(new java.awt.Color(6, 161, 196));
        labelMenuMinhaEstante.setText("Minha Estante");

        labelMenuConquistas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelMenuConquistas.setForeground(new java.awt.Color(6, 161, 196));
        labelMenuConquistas.setText("Conquistas");

        textAreaQualSuaDuvida.setColumns(20);
        textAreaQualSuaDuvida.setForeground(new java.awt.Color(153, 153, 153));
        textAreaQualSuaDuvida.setRows(5);
        textAreaQualSuaDuvida.setText("Qual sua dúvida?");
        textAreaQualSuaDuvida.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 161, 196), 1, true));
        textAreaQualSuaDuvida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textAreaQualSuaDuvidaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(textAreaQualSuaDuvida);

        labelMenuNotificacoes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelMenuNotificacoes.setForeground(new java.awt.Color(6, 161, 196));
        labelMenuNotificacoes.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelMenuNotificacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/notificacao.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(6, 161, 196));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estrutura de Dados", "Engenharia de Software", "Inglês" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Compartilhar:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(6, 161, 196));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Bate Papo");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(6, 161, 196), null));

        panelBGUltimosBadgetsFeedProf.setBackground(new java.awt.Color(6, 161, 196));

        labelUltimosBadgetsFeedProf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelUltimosBadgetsFeedProf.setForeground(new java.awt.Color(255, 255, 255));
        labelUltimosBadgetsFeedProf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUltimosBadgetsFeedProf.setText("Últimos Badgets");

        javax.swing.GroupLayout panelBGUltimosBadgetsFeedProfLayout = new javax.swing.GroupLayout(panelBGUltimosBadgetsFeedProf);
        panelBGUltimosBadgetsFeedProf.setLayout(panelBGUltimosBadgetsFeedProfLayout);
        panelBGUltimosBadgetsFeedProfLayout.setHorizontalGroup(
            panelBGUltimosBadgetsFeedProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelUltimosBadgetsFeedProf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBGUltimosBadgetsFeedProfLayout.setVerticalGroup(
            panelBGUltimosBadgetsFeedProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBGUltimosBadgetsFeedProfLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(labelUltimosBadgetsFeedProf)
                .addGap(29, 29, 29))
        );

        labelBadget1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBadget1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/badgets/primeiroCadastro.png"))); // NOI18N

        labelBadget2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBadget2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/badgets/primeiroLogin.png"))); // NOI18N

        labelBadget3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBadget3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/badgets/primeiros5Amigos.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBGUltimosBadgetsFeedProf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelBadget1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
            .addComponent(labelBadget2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelBadget3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(panelBGUltimosBadgetsFeedProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(labelBadget1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelBadget2)
                .addGap(18, 18, 18)
                .addComponent(labelBadget3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(6, 161, 196), null));

        lagelPergunta1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lagelPergunta1.setForeground(new java.awt.Color(6, 161, 196));
        lagelPergunta1.setText("Pergunta 1");

        panelBGUltimasPerguntasFeedProf.setBackground(new java.awt.Color(6, 161, 196));

        labelUltimasPerguntasFeedProf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelUltimasPerguntasFeedProf.setForeground(new java.awt.Color(255, 255, 255));
        labelUltimasPerguntasFeedProf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUltimasPerguntasFeedProf.setText("Últimas Perguntas");

        javax.swing.GroupLayout panelBGUltimasPerguntasFeedProfLayout = new javax.swing.GroupLayout(panelBGUltimasPerguntasFeedProf);
        panelBGUltimasPerguntasFeedProf.setLayout(panelBGUltimasPerguntasFeedProfLayout);
        panelBGUltimasPerguntasFeedProfLayout.setHorizontalGroup(
            panelBGUltimasPerguntasFeedProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelUltimasPerguntasFeedProf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBGUltimasPerguntasFeedProfLayout.setVerticalGroup(
            panelBGUltimasPerguntasFeedProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBGUltimasPerguntasFeedProfLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(labelUltimasPerguntasFeedProf)
                .addGap(23, 23, 23))
        );

        lagelPergunta2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lagelPergunta2.setForeground(new java.awt.Color(6, 161, 196));
        lagelPergunta2.setText("Pergunta 2");

        lagelPergunta3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lagelPergunta3.setForeground(new java.awt.Color(6, 161, 196));
        lagelPergunta3.setText("Pergunta 3");

        lagelPergunta4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lagelPergunta4.setForeground(new java.awt.Color(6, 161, 196));
        lagelPergunta4.setText("Pergunta 4");

        lagelPergunta5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lagelPergunta5.setForeground(new java.awt.Color(6, 161, 196));
        lagelPergunta5.setText("Pergunta 5");

        lagelPergunta6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lagelPergunta6.setForeground(new java.awt.Color(6, 161, 196));
        lagelPergunta6.setText("Pergunta 6");

        lagelPergunta7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lagelPergunta7.setForeground(new java.awt.Color(6, 161, 196));
        lagelPergunta7.setText("Pergunta 7");

        lagelPergunta8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lagelPergunta8.setForeground(new java.awt.Color(6, 161, 196));
        lagelPergunta8.setText("Pergunta 8");

        lagelPergunta9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lagelPergunta9.setForeground(new java.awt.Color(6, 161, 196));
        lagelPergunta9.setText("Pergunta 9");

        lagelPergunta10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lagelPergunta10.setForeground(new java.awt.Color(6, 161, 196));
        lagelPergunta10.setText("Pergunta 10");

        lagelPergunta11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lagelPergunta11.setForeground(new java.awt.Color(6, 161, 196));
        lagelPergunta11.setText("Pergunta 11");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lagelPergunta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lagelPergunta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lagelPergunta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lagelPergunta4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lagelPergunta5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lagelPergunta6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lagelPergunta7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lagelPergunta8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lagelPergunta9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lagelPergunta10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(lagelPergunta11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(panelBGUltimasPerguntasFeedProf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(panelBGUltimasPerguntasFeedProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lagelPergunta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lagelPergunta2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lagelPergunta3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lagelPergunta4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lagelPergunta5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lagelPergunta6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lagelPergunta7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lagelPergunta8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lagelPergunta9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lagelPergunta10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lagelPergunta11)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panelBGDuvidaPostada.setBackground(new java.awt.Color(255, 255, 255));
        panelBGDuvidaPostada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 161, 196)));

        panelBGRodapeDuvidaPostada.setBackground(new java.awt.Color(6, 161, 196));

        labelMateriaTopoDuvidaPostada1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelMateriaTopoDuvidaPostada1.setForeground(new java.awt.Color(255, 255, 255));
        labelMateriaTopoDuvidaPostada1.setText("Luiz Guilherme");

        jButton2.setBackground(new java.awt.Color(6, 161, 196));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Leia Mais");

        javax.swing.GroupLayout panelBGRodapeDuvidaPostadaLayout = new javax.swing.GroupLayout(panelBGRodapeDuvidaPostada);
        panelBGRodapeDuvidaPostada.setLayout(panelBGRodapeDuvidaPostadaLayout);
        panelBGRodapeDuvidaPostadaLayout.setHorizontalGroup(
            panelBGRodapeDuvidaPostadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBGRodapeDuvidaPostadaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMateriaTopoDuvidaPostada1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelBGRodapeDuvidaPostadaLayout.setVerticalGroup(
            panelBGRodapeDuvidaPostadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBGRodapeDuvidaPostadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBGRodapeDuvidaPostadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMateriaTopoDuvidaPostada1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBGTopoPerguntaPostada.setBackground(new java.awt.Color(6, 161, 196));

        labelMateriaTopoDuvidaPostada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelMateriaTopoDuvidaPostada.setForeground(new java.awt.Color(255, 255, 255));
        labelMateriaTopoDuvidaPostada.setText("Estrutura de Dados");

        labelProfessorTopoDuvidaPostada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelProfessorTopoDuvidaPostada.setForeground(new java.awt.Color(255, 255, 255));
        labelProfessorTopoDuvidaPostada.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelProfessorTopoDuvidaPostada.setText("Eduardo Enari");

        javax.swing.GroupLayout panelBGTopoPerguntaPostadaLayout = new javax.swing.GroupLayout(panelBGTopoPerguntaPostada);
        panelBGTopoPerguntaPostada.setLayout(panelBGTopoPerguntaPostadaLayout);
        panelBGTopoPerguntaPostadaLayout.setHorizontalGroup(
            panelBGTopoPerguntaPostadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBGTopoPerguntaPostadaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMateriaTopoDuvidaPostada, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelProfessorTopoDuvidaPostada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBGTopoPerguntaPostadaLayout.setVerticalGroup(
            panelBGTopoPerguntaPostadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBGTopoPerguntaPostadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBGTopoPerguntaPostadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMateriaTopoDuvidaPostada)
                    .addComponent(labelProfessorTopoDuvidaPostada))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(6, 161, 196));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("O que é Polimorfismo?");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Resposta aqui");

        javax.swing.GroupLayout panelBGDuvidaPostadaLayout = new javax.swing.GroupLayout(panelBGDuvidaPostada);
        panelBGDuvidaPostada.setLayout(panelBGDuvidaPostadaLayout);
        panelBGDuvidaPostadaLayout.setHorizontalGroup(
            panelBGDuvidaPostadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBGTopoPerguntaPostada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBGRodapeDuvidaPostada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBGDuvidaPostadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBGDuvidaPostadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBGDuvidaPostadaLayout.setVerticalGroup(
            panelBGDuvidaPostadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBGDuvidaPostadaLayout.createSequentialGroup()
                .addComponent(panelBGTopoPerguntaPostada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(panelBGRodapeDuvidaPostada, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTopoPaginaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelRodapePaginaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(labelMenuInicio)
                        .addGap(18, 18, 18)
                        .addComponent(labelMenuDisciplinas)
                        .addGap(18, 18, 18)
                        .addComponent(labelMenuCalendario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(6, 6, 6)
                .addComponent(labelMenuForum)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelMenuQuiz)
                        .addGap(18, 18, 18)
                        .addComponent(labelMenuMinhaEstante)
                        .addGap(18, 18, 18)
                        .addComponent(labelMenuConquistas)
                        .addGap(149, 149, 149)
                        .addComponent(labelMenuNotificacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)
                            .addComponent(panelBGDuvidaPostada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelTopoPaginaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMenuInicio)
                    .addComponent(labelMenuDisciplinas)
                    .addComponent(labelMenuCalendario)
                    .addComponent(labelMenuForum)
                    .addComponent(labelMenuQuiz)
                    .addComponent(labelMenuMinhaEstante)
                    .addComponent(labelMenuConquistas)
                    .addComponent(labelMenuNotificacoes))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(panelBGDuvidaPostada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelRodapePaginaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textAreaQualSuaDuvidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textAreaQualSuaDuvidaMouseClicked

        if(textAreaQualSuaDuvida.getText().equals("Qual sua dúvida?")) {
            textAreaQualSuaDuvida.setText("");
            repaint();
            revalidate();
        }
        
        textAreaQualSuaDuvida.setEditable(true);        
  
    }//GEN-LAST:event_textAreaQualSuaDuvidaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelImgTopoPaginaInicial;
    private javax.swing.JLabel jLabelRodapePaginaInicial;
    private javax.swing.JLabel jLabelTopoPaginaInicial;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelRodapePaginaInicial;
    private javax.swing.JPanel jPanelTopoPaginaInicial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBadget1;
    private javax.swing.JLabel labelBadget2;
    private javax.swing.JLabel labelBadget3;
    private javax.swing.JLabel labelMateriaTopoDuvidaPostada;
    private javax.swing.JLabel labelMateriaTopoDuvidaPostada1;
    private javax.swing.JLabel labelMenuCalendario;
    private javax.swing.JLabel labelMenuConquistas;
    private javax.swing.JLabel labelMenuDisciplinas;
    private javax.swing.JLabel labelMenuForum;
    private javax.swing.JLabel labelMenuInicio;
    private javax.swing.JLabel labelMenuMinhaEstante;
    private javax.swing.JLabel labelMenuNotificacoes;
    private javax.swing.JLabel labelMenuQuiz;
    private javax.swing.JLabel labelProfessorTopoDuvidaPostada;
    private javax.swing.JLabel labelUltimasConquistasFeedProf1;
    private javax.swing.JLabel labelUltimasConquistasFeedProf2;
    private javax.swing.JLabel labelUltimasPerguntasFeedProf;
    private javax.swing.JLabel labelUltimosBadgetsFeedProf;
    private javax.swing.JLabel lagelPergunta1;
    private javax.swing.JLabel lagelPergunta10;
    private javax.swing.JLabel lagelPergunta11;
    private javax.swing.JLabel lagelPergunta2;
    private javax.swing.JLabel lagelPergunta3;
    private javax.swing.JLabel lagelPergunta4;
    private javax.swing.JLabel lagelPergunta5;
    private javax.swing.JLabel lagelPergunta6;
    private javax.swing.JLabel lagelPergunta7;
    private javax.swing.JLabel lagelPergunta8;
    private javax.swing.JLabel lagelPergunta9;
    private javax.swing.JLabel lbTopoPaginaInicial;
    private javax.swing.JPanel panelBGDuvidaPostada;
    private javax.swing.JPanel panelBGRodapeDuvidaPostada;
    private javax.swing.JPanel panelBGTopoPerguntaPostada;
    private javax.swing.JPanel panelBGUltimasPerguntasFeedProf;
    private javax.swing.JPanel panelBGUltimosBadgetsFeedProf;
    private javax.swing.JPanel panelUltimasConquistasFeedProf1;
    private javax.swing.JTextArea textAreaQualSuaDuvida;
    // End of variables declaration//GEN-END:variables
}
